---
title: "Individual Rule Visualizations"
output: html_notebook
---

This is a notebook to look more at each rule.


# Looking at each rule


## VIBRANT
```{r}
vscore <- tibble(seqtype=viruses$seqtype,
                 vscore=rep(0, nrow(viruses)))

vscore$vscore[viruses$vibrant_quality=="high quality draft"] <- vscore$vscore[viruses$vibrant_quality=="high quality draft"] + 1
vscore$vscore[viruses$vibrant_quality=="medium quality draft"] <- vscore$vscore[viruses$vibrant_quality=="medium quality draft"] + 1
vscore$vscore[viruses$vibrant_quality=="low quality draft" & viruses$provirus] <- vscore$vscore[viruses$vibrant_quality=="low quality draft" & viruses$provirus] + 0.5

vscore$confusion_matrix <- "correct"
vscore$confusion_matrix[vscore$seqtype=="virus" & vscore$vscore<1] <- "false"
vscore$confusion_matrix[vscore$seqtype=="virus" & vscore$vscore>=1] <- "correct"
vscore$confusion_matrix[vscore$seqtype!="virus" & vscore$vscore>=1] <- "false"

table(vscore$seqtype, vscore$confusion_matrix)

pheatmap::pheatmap(table(vscore$seqtype, vscore$confusion_matrix)/c(rowSums(table(vscore$seqtype, vscore$confusion_matrix))),
                   color=c("black", viridis(1000)),
                   cluster_rows = F,
                   cluster_cols = F,
                   display_numbers = T,
                   number_color = "white", 
                   fontsize_number = 10)
```

## VirSorter2
```{r}
vscore <- tibble(seqtype=viruses$seqtype,
                 vscore=rep(0, nrow(viruses)))

vscore$vscore[viruses$max_score>=0.5] <- vscore$vscore[viruses$max_score>=0.5] + 0.5
vscore$vscore[viruses$max_score>=0.95] <- vscore$vscore[viruses$max_score>=0.95] + 0.5

vscore$confusion_matrix <- "correct"
vscore$confusion_matrix[vscore$seqtype=="virus" & vscore$vscore<1] <- "false"
vscore$confusion_matrix[vscore$seqtype=="virus" & vscore$vscore>=1] <- "correct"
vscore$confusion_matrix[vscore$seqtype!="virus" & vscore$vscore>=1] <- "false"

table(vscore$seqtype, vscore$confusion_matrix)

pheatmap::pheatmap(table(vscore$seqtype, vscore$confusion_matrix)/c(rowSums(table(vscore$seqtype, vscore$confusion_matrix))),
                   color=c("black", viridis(1000)),
                   cluster_rows = F,
                   cluster_cols = F,
                   display_numbers = T,
                   number_color = "white", 
                   fontsize_number = 10)
```

## VirSorter
```{r}
vscore <- tibble(seqtype=viruses$seqtype,
                 vscore=rep(0, nrow(viruses)))

vscore$vscore[viruses$category==1] <- vscore$vscore[viruses$category==1] + 1
vscore$vscore[viruses$category==2] <- vscore$vscore[viruses$category==2] + 0.5
vscore$vscore[viruses$category==4] <- vscore$vscore[viruses$category==4] + 1
vscore$vscore[viruses$category==5] <- vscore$vscore[viruses$category==5] + 0.5

vscore$confusion_matrix <- "correct"
vscore$confusion_matrix[vscore$seqtype=="virus" & vscore$vscore<1] <- "false"
vscore$confusion_matrix[vscore$seqtype=="virus" & vscore$vscore>=1] <- "correct"
vscore$confusion_matrix[vscore$seqtype!="virus" & vscore$vscore>=1] <- "false"

table(vscore$seqtype, vscore$confusion_matrix)

pheatmap::pheatmap(table(vscore$seqtype, vscore$confusion_matrix)/c(rowSums(table(vscore$seqtype, vscore$confusion_matrix))),
                   color=c("black", viridis(1000)),
                   cluster_rows = F,
                   cluster_cols = F,
                   display_numbers = T,
                   number_color = "white", 
                   fontsize_number = 10)
```

## DeepVirFinder
```{r}
vscore <- tibble(seqtype=viruses$seqtype,
                 vscore=rep(0, nrow(viruses)))

vscore$vscore[viruses$score>=0.7 & viruses$checkv_length<20000] <- vscore$vscore[viruses$score>=0.7 & viruses$checkv_length<20000] + 0.5
vscore$vscore[viruses$score>=0.9 & viruses$checkv_length<20000] <- vscore$vscore[viruses$score>=0.9 & viruses$checkv_length<20000] + 0.5

vscore$confusion_matrix <- "correct"
vscore$confusion_matrix[vscore$seqtype=="virus" & vscore$vscore<1] <- "false"
vscore$confusion_matrix[vscore$seqtype=="virus" & vscore$vscore>=1] <- "correct"
vscore$confusion_matrix[vscore$seqtype!="virus" & vscore$vscore>=1] <- "false"

table(vscore$seqtype, vscore$confusion_matrix)

pheatmap::pheatmap(table(vscore$seqtype, vscore$confusion_matrix)/c(rowSums(table(vscore$seqtype, vscore$confusion_matrix))),
                   color=c("black", viridis(1000)),
                   cluster_rows = F,
                   cluster_cols = F,
                   display_numbers = T,
                   number_color = "white", 
                   fontsize_number = 10)
```

## Tuning Addition
```{r}
vscore <- tibble(seqtype=viruses$seqtype,
                 vscore=rep(0, nrow(viruses)))

vscore$vscore[viruses$Kaiju_Viral=="Viruses"] <- vscore$vscore[viruses$Kaiju_Viral=="Viruses"] + 0.5
vscore$vscore[viruses$hallmark>2] <- vscore$vscore[viruses$hallmark>2] + 0.5
vscore$vscore[viruses$percent_unknown>=75 & viruses$checkv_length<50000] <- vscore$vscore[viruses$percent_unknown>=75 & viruses$checkv_length<50000] + 0.5
vscore$vscore[viruses$viral>=50] <- vscore$vscore[viruses$viral>=50] + 0.5

vscore$confusion_matrix <- "correct"
vscore$confusion_matrix[vscore$seqtype=="virus" & vscore$vscore<1] <- "false"
vscore$confusion_matrix[vscore$seqtype=="virus" & vscore$vscore>=1] <- "correct"
vscore$confusion_matrix[vscore$seqtype!="virus" & vscore$vscore>=1] <- "false"

table(vscore$seqtype, vscore$confusion_matrix)

pheatmap::pheatmap(table(vscore$seqtype, vscore$confusion_matrix)/c(rowSums(table(vscore$seqtype, vscore$confusion_matrix))),
                   color=c("black", viridis(1000)),
                   cluster_rows = F,
                   cluster_cols = F,
                   display_numbers = T,
                   number_color = "white", 
                   fontsize_number = 10,
                   number_format = "%.3f")
```

## Tuning Removal
```{r}
vscore <- tibble(seqtype=viruses$seqtype,
                 vscore=rep(1, nrow(viruses)))

#vscore$vscore[viruses$Kaiju_Viral=="cellular organisms"] <- vscore$vscore[viruses$Kaiju_Viral=="cellular organisms"] - 0.5
vscore$vscore[viruses$checkv_host_genes>50 & !viruses$provirus] <- vscore$vscore[viruses$checkv_host_genes>50 & !viruses$provirus] - 1
vscore$vscore[viruses$checkv_viral_genes==0 & viruses$checkv_host_genes>=1] <- vscore$vscore[viruses$checkv_viral_genes==0 & viruses$checkv_host_genes>=1] - 1
vscore$vscore[((viruses$checkv_viral_genes*3) <= viruses$checkv_host_genes) & !viruses$provirus] <- vscore$vscore[((viruses$checkv_viral_genes*3) <= viruses$checkv_host_genes) & !viruses$provirus] - 1 
vscore$vscore[viruses$checkv_length>500000 & viruses$hallmark<=1] <- vscore$vscore[viruses$checkv_length>500000 & viruses$hallmark<=1] - 1
vscore$vscore[(viruses$checkv_completeness<=75 | viruses$vibrant_quality=="complete circular")& viruses$checkv_length<=5000] <- vscore$vscore[viruses$checkv_completeness<=75 & viruses$checkv_length<=5000] - 0.5

vscore$confusion_matrix <- "correct"
vscore$confusion_matrix[vscore$seqtype=="virus" & vscore$vscore<1] <- "false"
vscore$confusion_matrix[vscore$seqtype=="virus" & vscore$vscore>=1] <- "correct"
vscore$confusion_matrix[vscore$seqtype!="virus" & vscore$vscore>=1] <- "false"

table(vscore$seqtype, vscore$confusion_matrix)

pheatmap::pheatmap(table(vscore$seqtype, vscore$confusion_matrix)/c(rowSums(table(vscore$seqtype, vscore$confusion_matrix))),
                   color=c("black", viridis(1000)),
                   cluster_rows = F,
                   cluster_cols = F,
                   display_numbers = T,
                   number_color = "white", 
                   fontsize_number = 10)
```




